# Generated by Django 3.2.7 on 2021-10-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_img', models.ImageField(upload_to='picture')),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
            ],
        ),
    ]
