# Generated by Django 3.2.7 on 2021-10-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_img', models.ImageField(upload_to='picture')),
                ('client_caption', models.TextField()),
                ('client_name', models.CharField(max_length=20)),
            ],
        ),
    ]
